package com.armored.pigeon.frames;

import com.armored.pigeon.server.*;
import com.armored.pigeon.cache.*;
import com.armored.pigeon.DTO.*;
import java.net.Socket;
import java.awt.*;
import java.io.*;
import java.net.*;
import javax.swing.WindowConstants;


public class FriendRequestFrame extends javax.swing.JFrame {

    /**
     * Creates new form FriendRequestFrame
     */
    
    private UserCache user;
    private userDTO friend;
    
            
    public FriendRequestFrame() {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        this.setName("FriendRequestFrame");
    }

    public void setInfo(){
        this.senderNameLabel.setText("Sender's Name = "+friend.getName());
        this.senderIDLabel.setText("Sender's ID = "+friend.getLoginID());
    }

    public UserCache getUser() {
        return user;
    }

    public void setUser(UserCache user) {
        this.user = user;
    }

    public userDTO getFriend() {
        return friend;
    }

    public void setFriend(userDTO friend) {
        this.friend = friend;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        senderNameLabel = new javax.swing.JLabel();
        senderIDLabel = new javax.swing.JLabel();
        acceptRequestBtn = new javax.swing.JButton();
        RejectRequest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Friend Request");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));

        senderNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        senderNameLabel.setForeground(new java.awt.Color(255, 255, 255));

        senderIDLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        senderIDLabel.setForeground(new java.awt.Color(255, 255, 255));

        acceptRequestBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        acceptRequestBtn.setForeground(new java.awt.Color(255, 255, 255));
        acceptRequestBtn.setText("Accept");
        acceptRequestBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        acceptRequestBtn.setContentAreaFilled(false);
        acceptRequestBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptRequestBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acceptRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptRequestBtnActionPerformed(evt);
            }
        });

        RejectRequest.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        RejectRequest.setForeground(new java.awt.Color(255, 255, 255));
        RejectRequest.setText("Reject");
        RejectRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        RejectRequest.setContentAreaFilled(false);
        RejectRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RejectRequest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RejectRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(acceptRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(RejectRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(senderIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(senderNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(senderNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senderIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RejectRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RejectRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectRequestActionPerformed
        try{
            Socket socket = APServerConnector.getConnection();
            APServerOPInitializer aps = new APServerOPInitializer();
            APServerPacketSender apSend = new APServerPacketSender(socket);
            APServerUtilities apUtil = new APServerUtilities();
            
            aps.setOperationCode("REQ000");
            aps.setMsgString(friend.getLoginID() + "," + user.getLoginId());
            
            byte[] outArr = apUtil.convertToBytes(aps);
            
            apSend.sendPacketSize(outArr.length);
            apSend.send(outArr);
            
            user.removeRequest(friend);
            
        }catch(Exception e){
            e.printStackTrace();
        }
        this.setVisible(false);
    }//GEN-LAST:event_RejectRequestActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void acceptRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptRequestBtnActionPerformed
        try{
            Socket socket = APServerConnector.getConnection();
            APServerOPInitializer aps = new APServerOPInitializer();
            APServerPacketSender apSend = new APServerPacketSender(socket);
            //APServerPacketReceiver apReceive = new APServerPacketReceiver(socket);
            APServerUtilities apUtil = new APServerUtilities();
            
            aps.setOperationCode("REQ001");
System.out.println("friend Sent = "+friend.getName());
            aps.setMsgString(friend.getLoginID() + "," + user.getLoginId());
            
            byte[] outArr = apUtil.convertToBytes(aps);
            
            apSend.sendPacketSize(outArr.length);
            apSend.send(outArr);
            
            user.addFriend(friend);
            user.removeRequest(friend);
            
            CacheProcessor writer = new CacheProcessor(user.getLoginId());
            writer.updateCache(user);
            
        }catch(Exception e){
            e.printStackTrace();
        }
        this.setVisible(false);
    }//GEN-LAST:event_acceptRequestBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FriendRequestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FriendRequestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FriendRequestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FriendRequestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FriendRequestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RejectRequest;
    private javax.swing.JButton acceptRequestBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel senderIDLabel;
    private javax.swing.JLabel senderNameLabel;
    // End of variables declaration//GEN-END:variables
}
