package com.armored.pigeon.frames;


import javafx.scene.paint.Color;
import java.awt.Font;
import java.util.regex.Pattern;
import javax.swing.*;

import com.armored.pigeon.DTO.*;
import com.armored.pigeon.server.*;
import java.awt.Frame;
import java.awt.Toolkit;
import java.net.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;



public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public LoginFrame() {
        initComponents();
        errorLabel.setVisible(false);
        this.setName("LoginFrame");
        //this.loginField.setText("Gaurav@123");
        //this.passwordField.setText("123456");
        APServerConnector.getConnection();
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        passwordLine = new javax.swing.JSeparator();
        loginLine = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        exitPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 26, 26));
        setForeground(new java.awt.Color(26, 26, 26));
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 20, 23));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(253, 251, 249));
        loginLabel.setText("Login ID");
        loginLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        loginLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel1.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 90, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(253, 251, 249));
        passwordLabel.setText("Password");
        passwordLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        passwordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        passwordLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, -1));

        loginField.setBackground(new java.awt.Color(19, 20, 23));
        loginField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginField.setForeground(new java.awt.Color(255, 255, 255));
        loginField.setBorder(null);
        loginField.setMargin(new java.awt.Insets(2, 5, 2, 2));
        loginField.setOpaque(false);
        loginField.setPreferredSize(new java.awt.Dimension(170, 30));
        loginField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        loginField.setSelectionColor(new java.awt.Color(143, 171, 182));
        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });
        jPanel1.add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 370, 40));

        passwordField.setBackground(new java.awt.Color(19, 20, 23));
        passwordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(null);
        passwordField.setEchoChar('\u25CF');
        passwordField.setMargin(new java.awt.Insets(2, 5, 2, 2));
        passwordField.setOpaque(false);
        passwordField.setPreferredSize(new java.awt.Dimension(170, 30));
        passwordField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        passwordField.setSelectionColor(new java.awt.Color(143, 171, 182));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 370, 40));

        loginBtn.setBackground(new java.awt.Color(26, 26, 26));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(253, 253, 253));
        loginBtn.setText("Login");
        loginBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setPreferredSize(new java.awt.Dimension(60, 25));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 370, 47));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 251, 249));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("New to Armored Pigeon?");
        jLabel4.setPreferredSize(new java.awt.Dimension(125, 14));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 137, 20));

        registerLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register Now");
        registerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerLabel.setPreferredSize(new java.awt.Dimension(70, 14));
        registerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                registerLabelMouseMoved(evt);
            }
        });
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerLabelMouseExited(evt);
            }
        });
        jPanel1.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 80, 20));

        errorLabel.setBackground(new java.awt.Color(255, 151, 151));
        errorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(226, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 0, 0), 1, true));
        errorLabel.setOpaque(true);
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 370, 40));
        jPanel1.add(passwordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 370, 10));
        jPanel1.add(loginLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 370, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 10, 400));

        exitPanel.setBackground(new java.awt.Color(19, 20, 23));
        exitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(102, 102, 102));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/armored/pigeon/icons/icons8-close-25.png"))); // NOI18N
        exitBtn.setToolTipText("Close");
        exitBtn.setAlignmentX(0.5F);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn.setIconTextGap(2);
        exitBtn.setMargin(new java.awt.Insets(3, 3, 3, 3));
        exitBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        exitPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        jPanel1.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 35));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/armored/pigeon/icons/AP 370 X 370.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 370, 370));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(143, 171, 182));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Armored Pigeon");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 340, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
         errorLabel.setVisible(false);
        String loginId = loginField.getText();
        String pass = new String(passwordField.getPassword());
        int password = 0;
        if(Pattern.matches("\\d+", pass)){
            password = Integer.parseInt(pass);
        }else{
            errorLabel.setVisible(true);
            errorLabel.setText("Password must be a Number");
            return;
        }
        
        //GETTING IP OF SYSTEM
        String ip = "";
        try{
            InetAddress host = InetAddress.getLocalHost();
            ip = host.getHostAddress().trim();
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        //OPINITIALIZER
        APServerOPInitializer aps = new APServerOPInitializer();
        aps.setOperationCode("DSK002");
        aps.setMsgString(loginId + "," + password + "," + ip);
        
        APServerUtilities apUtil = new APServerUtilities();
        
        APServerOPInitializer bytesIn = new APServerOPInitializer();
        //CONVERTING USER DTO TO BYTEARRAY
        
        Socket socket = null;
        try{
            socket = APServerConnector.getConnection();
            APServerPacketSender apSend = new APServerPacketSender(socket);
            APServerPacketReceiver apReceive = new APServerPacketReceiver(socket);
            byte[] apArr = apUtil.convertToBytes(aps);
            int len = apArr.length;
            
            //SENDING LENGTH
            apSend.sendPacketSize(len);
            
            //SENDING DATA
            apSend.send(apArr);
            
            //RECEIVING RESPONSE
            int receivedLen = apReceive.receivePacketSize();
            //System.out.println("received length in Login : "+receivedLen);
            
            //RECEIVING PACKET
            byte[] serverIn = apReceive.receive(receivedLen);
            bytesIn = (APServerOPInitializer)apUtil.convertFromBytes(serverIn);
            
            //socket.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        String response[] = bytesIn.getMsgString().split(",");
        
        //System.out.println("No of Messages = "+response[2]);
        
        if(bytesIn.getOperationCode().equals("SRV010")){
            String res = response[0];
            if(res.equalsIgnoreCase("true")){
                ChatFrame.loginId = loginId;
                //ChatFrame chatFrame = new ChatFrame();
                ChatFrame.main(new String[0]);
                ChatFrame.response = response[1];
                this.setVisible(false);

            }else{
                if(res.equalsIgnoreCase("active")){
                    errorLabel.setVisible(true);
                    errorLabel.setText("User already Active");
                }else{
                    errorLabel.setVisible(true);
                    errorLabel.setText("Register yourself");
                }
            }
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed
        
    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    private void registerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseClicked
        RegisterFrame rFrame = new RegisterFrame();
        rFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerLabelMouseClicked

    private void registerLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseMoved
        registerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Font f = new Font("Segoe UI",Font.BOLD,12);
        registerLabel.setFont(f);
    }//GEN-LAST:event_registerLabelMouseMoved

    private void registerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseExited
        Font f = new Font("Segoe UI",Font.PLAIN,12);
        registerLabel.setFont(f);
    }//GEN-LAST:event_registerLabelMouseExited

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        this.loginBtn.setForeground(new java.awt.Color(26, 170, 92));
        this.loginBtn.setBorder(new LineBorder(new java.awt.Color(26, 170, 92),2,false));
    }//GEN-LAST:event_loginBtnMouseEntered

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        try{
        Socket socket = APServerConnector.getConnection();
        APServerOPInitializer aps = new APServerOPInitializer();
        APServerPacketSender apSend = new APServerPacketSender(socket);
        APServerUtilities apUtil = new APServerUtilities();
        
        aps.setOperationCode("DSK404");
        aps.setMsgString("");
        byte[] arr = apUtil.convertToBytes(aps);
        apSend.sendPacketSize(arr.length);
        apSend.send(arr);
        System.out.println("IN Finalize");
        socket.close();
        APServerConnector.closeConnection();
        }catch(Exception e){
            e.printStackTrace();
        }
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        this.loginBtn.setForeground(new java.awt.Color(253, 253, 253));
        this.loginBtn.setBorder(new LineBorder(new java.awt.Color(253, 253, 253),2,false));
    }//GEN-LAST:event_loginBtnMouseExited

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        this.exitPanel.setBackground(new java.awt.Color(232, 17, 35));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        this.exitPanel.setBackground(new java.awt.Color(19, 20, 23));
    }//GEN-LAST:event_exitBtnMouseExited

    public Frame fetchFrame(String name){
        Frame[] frames = Frame.getFrames();
        for(Frame n: frames){
            if(n.getName().equals(name)){
                return n;
            }
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
        ApListener ap = new ApListener();
        ap.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JSeparator loginLine;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JSeparator passwordLine;
    private javax.swing.JLabel registerLabel;
    // End of variables declaration//GEN-END:variables
}
